services:
  lapis:
    image: mileschou/lapis
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    working_dir: /app
    command: /bin/bash

# To run it: try `sudo docker compose run --rm lapis`
